<a href="https://colab.research.google.com/github/arka57/CNN/blob/main/Potato_Disease_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from PIL import Image
import torchvision as tv
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset, random_split
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import torchvision

In [2]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [6]:
cd MyDrive

/gdrive/MyDrive


In [8]:
pwd

'/gdrive/MyDrive'

In [9]:
#Data PreProcessing

In [10]:
transform = transforms.Compose([
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

In [ ]:
#Loading the dataset 

In [11]:
full_data = tv.datasets.ImageFolder(root="Potato_Disease_Classification",transform=transform)

In [12]:
full_data

Dataset ImageFolder
    Number of datapoints: 2152
    Root location: Potato_Disease_Classification
    StandardTransform
Transform: Compose(
               RandomResizedCrop(size=(224, 224), scale=(0.08, 1.0), ratio=(0.75, 1.3333), interpolation=bilinear, antialias=warn)
               RandomHorizontalFlip(p=0.5)
               ToTensor()
               Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
           )

In [13]:
full_data[2004]

(tensor([[[ 1.1872,  0.8104,  0.4851,  ..., -0.1143, -0.1828, -0.1828],
          [ 1.1015,  0.5707,  0.1083,  ...,  0.3309, -0.0629, -0.4739],
          [ 0.6563,  0.2111, -0.1486,  ...,  0.2967,  0.0227, -0.3198],
          ...,
          [ 0.9474,  0.9817,  0.9988,  ...,  0.9303,  0.9988,  1.0331],
          [ 0.9646,  0.9988,  0.9988,  ...,  0.9646,  0.9817,  0.9817],
          [ 1.0331,  1.0331,  1.0159,  ...,  0.9303,  0.9132,  0.8961]],
 
         [[ 1.1331,  0.7479,  0.4153,  ...,  0.3803,  0.3277,  0.3277],
          [ 1.0455,  0.5028,  0.0301,  ...,  0.8529,  0.4503,  0.0301],
          [ 0.5903,  0.1352, -0.2325,  ...,  0.8179,  0.5378,  0.1877],
          ...,
          [ 0.9930,  1.0280,  1.0455,  ...,  0.9055,  0.9755,  1.0105],
          [ 1.0105,  1.0455,  1.0455,  ...,  0.9405,  0.9580,  0.9580],
          [ 1.0805,  1.0805,  1.0630,  ...,  0.9055,  0.8880,  0.8704]],
 
         [[ 1.4200,  1.0365,  0.7054,  ..., -0.1138, -0.2184, -0.2532],
          [ 1.3328,  0.7925,

In [ ]:
#Splitting the dataset into train and test

In [14]:
train_size = int(0.8 * len(full_data))
test_size = len(full_data) - train_size

In [15]:
train_data, test_data = random_split(full_data, [train_size, test_size])

train_loader = torch.utils.data.DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_data, batch_size=32, shuffle=True)

In [16]:
for i in train_loader:
    images,labels=i
    print(images.shape)
    print(labels)
    break

torch.Size([32, 3, 224, 224])
tensor([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 1, 1])


In [18]:
labels

tensor([0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 1, 1])

In [22]:
len(train_loader)

54

In [ ]:
#Defining the model

In [ ]:
class LeNet(nn.Module):
    def __init__(self):
        super(LeNet,self).__init__(self)
        self.cnn=nn.Sequential(
            nn.Conv2d(3,6,(5,5)),
            nn.Avgpool2d(2,stride=2),
            nn.ReLu(),
            nn.Conv2d(6,16,(5,5)),
            nn.Avgpool2d(2,stride=2),
            nn.ReLu(),
            nn.Conv2d(16,8,(5,5)),
            nn.Avgpool2d(2,stride=2),
            nn.ReLu(),
            nn.Conv2d(8,4,(5,5)),
            nn.Avgpool2d(2,stride=2),
            nn.ReLu(),

        )
        self.fc=nn.Sequential(
            nn.Linear(400,2000),
            nn.ReLu(),
            nn.Linear(200,80),
            nn.ReLu(),
            nn.Linear(80,3)
        )
    def forward(self,x);
        =self.cnn(x)
        x=x.view(x.size(0),-1)
        x=self.fc(x)
        return x



In [ ]:
#Evaluation


In [ ]:
def evaluation(dataloader):
    total=0
    correct=0
    for i,data in enumerate(dataloader):
        input,label=data
        output=net.forward(input)
        _,pred=torch.max(output,1)
        total+=label(0).size()
        correct+=(output==label).sum().item()
    return (correct/output)*100    

In [ ]:
#Learning algo

In [ ]:
loss_epoch=[]
for i in range(0,epoch):
    for j,data in enumerate(trainloader,0):
        input,label=data
        output=net.forward(input)
        loss=loss_fn(output,label)
        loss.backward()
        opt.step()
        opt.zero_grad()
    loss_epoch.append(loss.item())
    print('Epoch %d/%d ,Training accuracy %0.2f,Test Accuracy %0.2f' %(i,epoch,evaluation(trainloader),evaluation(testloader)))

plt.plot(loss_epoch)
plt.show()        